services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${HOMEPATH}qbittorrent/config:/config
      - ${HOMEPATH}Downloads:/downloads
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    healthcheck:
      start_period: 15s
    depends_on:
      - tailscale
    network_mode: service:tailscale
