services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "67:67/udp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PASSWORD} 
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "${HOMEPATH}Pihole:/etc/pihole"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

