services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ${HOMEPATH}Prowlarr/config:/config
      - ${HOMEPATH}Prowlarr/backup:/data/Backup
      - ${HOMEPATH}Downloads:/downloads
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ${HOMEPATH}Sonarr/config:/config
      - ${HOMEPATH}Sonarr/backup:/data/Backup
      - ${HOMEPATH}Sonarr/tvshows:/data/tvshows
      - ${HOMEPATH}Downloads:/downloads
    environment:
      - PUID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ${HOMEPATH}Radarr/config:/config
      - ${HOMEPATH}Radarr/movies:/data/movies
      - ${HOMEPATH}Radarr/backup:/data/Backup
      - ${HOMEPATH}Downloads:/downloads
    environment:
      - PUID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - ${HOMEPATH}Lidarr/config:/config
      - ${HOMEPATH}Lidarr/music:/data/music
      - ${HOMEPATH}Lidarr/backup:/data/Backup
      - ${HOMEPATH}Downloads:/downloads
    environment:
      - PUID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - ${HOMEPATH}Readarr/config:/config
      - ${HOMEPATH}Readarr/books:/data/books
      - ${HOMEPATH}Readarr/backup:/data/Backup
      - ${HOMEPATH}Downloads:/downloads
    environment:
      - PUID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    volumes:
      - ${HOMEPATH}Jellyfin/config:/config
      - ${HOMEPATH}Radarr/movies:/data/Movies
      - ${HOMEPATH}Sonarr/tvshows:/data/TVShows
      - ${HOMEPATH}Lidarr/music:/data/Music
      - ${HOMEPATH}Readarr/books:/data/Books
    environment:
      - PUID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale
