services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale
    environment:
      - TS_AUTHKEY=${TAILSCALE_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-exit-node
    volumes:
      - ${HOMEPATH}/Tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    ports:
      - "2342:2342"       # PhotoPrism
      - "9696:9696"       # Prowlarr
      - "8989:8989"       # Sonarr
      - "7878:7878"       # Radarr
      - "8686:8686"       # Lidarr
      - "8787:8787"       # Readarr
      - "7575:7575"       # Homearr
      - "8096:8096/tcp"   # Jellyfin web interface
      - "7359:7359/udp"   # Network discovery
      - "1900:1900/udp"   # DLNA port
      - "8080:8080"       # QBittorent
      - "6881:6881"       # QBittorent
      - "6881:6881/udp"   # QBittorent
      - "9443:9443"       # Portainer
