services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMEPATH}Portainer/data:/data
    depends_on:
      - tailscale
    network_mode: service:tailscale
