services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
      - tailscale
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_USER: ${USERNAME}
      PHOTOPRISM_ADMIN_PASSWORD: ${PASSWORD}
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: ${USERNAME}
      PHOTOPRISM_DATABASE_PASSWORD: ${PASSWORD}
      PHOTOPRISM_FFMPEG_SIZE: "7680"
      PHOTOPRISM_FFMPEG_BITRATE: "50"
      PHOTOPRISM_INIT: "https gpu tensorflow"
      PHOTOPRISM_UID: ${PUID}
      PHOTOPRISM_GID: ${PGID}
    user: ${PUID}:${PGID}
    working_dir: "/photoprism"
    volumes:
      - ${HOMEPATH}Photoprism/Pictures:/photoprism/originals
      - ${HOMEPATH}Photoprism/storage:/photoprism/storage
    network_mode: service:tailscale

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - ${HOMEPATH}Photoprism/database:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: ${USERNAME}
      MARIADB_PASSWORD: ${PASSWORD}
      MARIADB_ROOT_PASSWORD: ${PASSWORD}
